#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     controllers,    sensorNone)
#pragma config(Sensor, S2,     light,         sensorCOLORNONE)
#pragma config(Sensor, S3,     irSeek,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ultrasonicSensor, sensorSONAR)
#pragma config(Motor,  motorA,          flickMotor1,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          flickMotor2,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     hangMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     empty1,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagRaiser,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    releaseServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    pinServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    blockServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    trayR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    trayL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    flagServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

bool useTemplate = true;

// Handy move method with speed and offset.
void move(int speed, int offset)
{
	speed = speed * -1;
	speed = speed - offset;

	// Turn right if offset >0, so power left motor.
	motor[left] = (speed + offset) * -1;
	motor[right] = speed - offset;

}

void stopMoving()
{
	motor[right] = 0;
	motor[left] = 0;
}

void moveUntilSpace(int distance, int speed)
{
	// should be positives
	move(speed,0);
	while(SensorValue[ultrasonicSensor] < distance)
	{
		// do nothing
	}
	stopMoving();
}


string off = "off";
string red = "red";
string green = "green";
string blue = "blue";
void setLight(string color)
{
	if(strcmp(color, "off") == 0)
	{
		SensorType[light] = sensorCOLORNONE;
	}
	if(strcmp(color, "red") == 0)
	{
		SensorType[light] = sensorCOLORRED;
	}
	if(strcmp(color, "green") == 0)
	{
		SensorType[light] = sensorCOLORGREEN;
	}
	if(strcmp(color, "blue") == 0)
	{
		SensorType[light] = sensorCOLORBLUE;
	}
}








int startBlockServo = 0;
int waitTime;
void setup(bool selectWait)
{
	setLight(red);
	// 1 = right 2 = left
	// Select wait time
	if(selectWait)
	{
		while(true)
		{
			if(nNxtButtonPressed == 1)
			{
				// wait 10 seconds
				waitTime = 10000;
				break;
			}
			if(nNxtButtonPressed == 2)
			{
				waitTime = 0;
				break;
			}
		}
	}
	servo[blockServo] = startBlockServo;
	servo[pinServo] = 123;
	int trayPosition = 70;
	servo[trayR] = trayPosition;
	servo[trayL] = 255 - trayPosition;

	setLight(green);

}


// Measure and set this value so it is correct.
  // This value is the amount of time it takes to get to the middle of the crates thingy.
int middleTime = 1450;
long timeMoved = 15;
void moveUntilBeacon(int valueToCompare, int speed)
{
	// should be negative
	move(speed,0);
	while(SensorValue[irSeek] != valueToCompare)
	{
		if(time1[T1] > middleTime)
		{
			setLight(blue);
		}
		else
		{
			setLight(green);
		}
	}

}

task main()
{
	setup(true);

  if(useTemplate)
  {
  	waitForStart(); // Wait for the beginning of autonomous phase.
  }
  // Wait for a certain amount of time before moving
  wait1Msec(waitTime);



	// Light should be green until robot passes the middle


  ClearTimer(T1);
  // Move at full speed, twoards the crates
  moveUntilBeacon(4, 100);
  timeMoved = time1[T1];
  // If we arent past the middle, move a little bit more (but slowly)
  move(30,0);

  // Store the amount of time to wait in here
  int wait = 0;
  if(timeMoved < middleTime)
  {
  	wait = 300;
	}
	else
	{
		wait = 200;
	}

	wait1Msec(wait);
  timeMoved+=wait/2;

  stopMoving();
  //timeMoved = time1[T1];



  // Chuck the block
  servo[blockServo] = 255;
  wait1Msec(2000);
  servo[blockServo] = startBlockServo;



  // Move backwards

  move(-100, 0);
  wait1Msec(timeMoved - 50);
  stopMoving();
  //wait1Msec(100000);



  // Turn to go alongside the ramp
	//move(100, 200);
  motor[right] = -100;
	motor[left] = -100;
	wait1Msec(700);
	stopMoving();

	// Move forward alongside ramp

	move(-100, 0);
	wait1Msec(1500);
	stopMoving();

	// turn to ramp
	motor[right] = -100;
	motor[left] = -100;
	wait1Msec(1000);
	stopMoving();

	// Move forward up ramp

	move(-100, 0);
	wait1Msec(1700);
	stopMoving();


  /*
  Sequence:

  Auto1:
  - Setup
  - WaitForStart
  - Wait
  - Move forward until beacon is found
  - Dump block
  - Move backward
  - Turn right 90*
  - Go forward for a bit
  - Go forward until a space on the ramp is found
  - Turn left
  - Move forward on to ramp

  Auto2:
  - Setup
  - WaitForStart
  - Wait
  - Move backward until beacon is found
  - Dump block
  - Move forward
  - Turn right 90*
  - Go forward for a bit
  - Go forward until a space on the ramp is found
  - Turn right
  - Move forward on to ramp

  */

  // Comment this out until we know how much to turn.
  /*
  // turn twoars clay
  move(100, -100);
  wait1Msec(720);
  stopMoving();



  // Turn twoards ramp
  move(100, 100);

  wait1Msec(700);
  stopMoving();



  // Move forward for a bit
  move(100, 0);
  wait1Msec(800);
  stopMoving();

  // Move until a space is found
  // Play around with this value, it corresponds to centimeters
  moveUntilSpace(120, 100);


  // Keep moving for a bit
  move(100, 0);
  wait1Msec(100);
  stopMoving();




  // Turn to ramp
  move(100, -100);
  wait1Msec(800);
  stopMoving();



  // Move forward up ramp
  move(100, 0);
  wait1Msec(1800);
  stopMoving();



  /* This is no longer needed.
  // Remove the pins
	servo[pinServo] = 0;
	wait1Msec(2000);
	servo[pinServo] = 255;
	wait1Msec(2000);
	servo[pinServo] = 255/2;*/



}
