#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task main()
{

	while (true)
	{
		getJoystickSettings(joystick);

		int right = joystick.joy1_y2;
		int left = joystick.joy1_y1;

		if(abs(right) < 10) right = 0;
		if(abs(left) < 10) left = 0;

		motor[rightMotor] = right;
		motor[leftMotor] = left;

	}
}
