#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     r1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     r2,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     l1,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     l2,            tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    s1,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    s2,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    empty,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    empty,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    empty,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    empty,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task main()
{

	while (true)
	{
		getJoystickSettings(joystick);

		int power = joystick.joy1_y1;
		int turn = joystick.joy1_x2;
		//if(abs(turn) < 5) turn = 0;
		if(abs(power) < 5) power = 0;

		if(power > 0)
		{
			motor[r1] = (power * -1) + (turn/2);
			motor[r2] = (power) + (turn/2);

			motor[l1] = (power) - (turn/2);
			motor[l2] = (power) - (turn/2);
		}
		else if(power < 0)
		{
			motor[r1] = (power * -1) - (turn/2);
			motor[r2] = (power) - (turn/2);

			motor[l1] = (power) + (turn/2);
			motor[l2] = (power) + (turn/2);
		}
		else
		{
			motor[r1] = 0;
			motor[r2] = 0;

			motor[l1] = 0;
			motor[l2] = 0;
		}
		servo[s1] = 128 - (turn * .4);
		servo[s2] = 128 - (turn * .4);
		wait1Msec(50);
	}
}
