#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// true maximum is  (+-)min + max
	int max = 1000;
	int min = 300;
while(true)
{
	if(SensorValue[light] > 40)
	{
		motor[right] = 100;
		motor[left] = 100;
	}
  else
	{
		motor[right] = -70;
		motor[left] = -70;
		wait1Msec(700);

		int r = random(max) - max/2;

		writeDebugStreamLine("%d", r);

		if(r > 0)
		{
			motor[right] = -70;
			motor[left] = 70;
			wait1Msec(r + min);
		}
		else
		{
			motor[right] = 70;
			motor[left] = -70;
			wait1Msec(abs(r - min));
		}
	}
}
// value > 40 go straigut

}
